dist: trusty
os: linux

language: java
jdk:
  - oraclejdk8

install: true

before_install:
  - chmod +x gradlew

script:
  ./gradlew shadowJar

before_cache:
    - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

after_script:
  - find .

cache:
  bundler: true
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
