dist: trusty
os: linux

language: java
jdk:
  - oraclejdk8

deploy:
  porvider: releases
  api_key: $GHA
  file: quoter.jar
  skip_cleanup: true
  draft: false

install: true

before_install:
  - chmod +x gradlew

script:
  ./gradlew shadowJar

before_cache:
    - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

after_script:
  - mv `find build/libs -name "*.jar" | head -n 1` quoter.jar

cache:
  bundler: true
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
